In [1]:
import pandas as pd
microsoft_df=pd.read_csv('Microsoft_Data.csv')

Total = microsoft_df.isnull().sum().sort_values(ascending=False)
Percentage = (microsoft_df.isnull().sum()*100)/microsoft_df.isnull().count().sort_values(ascending=False)
missing_values = pd.concat([Total,Percentage],keys=['Total','Percentage'],axis=1,sort=False).sort_values('Total',ascending=False)
missing_values
microsoft_df.drop(columns=['MachineIdentifier','PuaMode','Census_ProcessorClass','DefaultBrowsersIdentifier','Census_IsFlightingInternal','Census_InternalBatteryType','Census_ThresholdOptIn','Census_IsWIMBootEnabled'],inplace=True)
        

    
for col in microsoft_df.columns:
    if microsoft_df[col].isnull().sum() > 10000:
        microsoft_df.drop(col,axis=1,inplace=True)


microsoft_df_dtypes={'object':[col for col in microsoft_df.columns if microsoft_df[col].dtype =='object'],'int or float':[col for col in microsoft_df.columns if microsoft_df[col].dtype =='float64']}

for col in microsoft_df_dtypes['object']:
    microsoft_df[col].fillna(value=microsoft_df[col].mode()[0],inplace=True)
    
for col in microsoft_df_dtypes['int or float']:
    microsoft_df[col].fillna(value=microsoft_df[col].median(),inplace=True)
    


values={'RtpStateBitfield':microsoft_df['RtpStateBitfield'].mode().iloc[0],
       'AVProductStatesIdentifier':microsoft_df['AVProductStatesIdentifier'].mode().iloc[0],
       'AVProductsInstalled':microsoft_df['AVProductsInstalled'].mode().iloc[0],
       'AVProductsEnabled':microsoft_df['AVProductsEnabled'].mode().iloc[0],
       'CityIdentifier':microsoft_df['CityIdentifier'].mode().iloc[0],
        'OrganizationIdentifier':microsoft_df['OrganizationIdentifier'].mode().iloc[0],
        'IsProtected':microsoft_df['IsProtected'].mode().iloc[0],
         'Wdft_RegionIdentifier':microsoft_df['Wdft_RegionIdentifier'].mode().iloc[0],
        'Census_IsAlwaysOnAlwaysConnectedCapable':microsoft_df['Census_IsAlwaysOnAlwaysConnectedCapable'].mode().iloc[0],
        'Census_IsVirtualDevice':microsoft_df['Census_IsVirtualDevice'].mode().iloc[0],
        'Census_FirmwareVersionIdentifier':microsoft_df['Census_FirmwareVersionIdentifier'].mode().iloc[0],
        'Census_FirmwareManufacturerIdentifier':microsoft_df['Census_FirmwareManufacturerIdentifier'].mode().iloc[0],
        'Census_IsFlightsDisabled':microsoft_df['Census_IsFlightsDisabled'].mode().iloc[0],
        'Census_OSInstallLanguageIdentifier':microsoft_df['Census_OSInstallLanguageIdentifier'].mode().iloc[0],
         'Census_InternalBatteryNumberOfCharges':microsoft_df['Census_InternalBatteryNumberOfCharges'].mode().iloc[0],
         'Census_InternalPrimaryDisplayResolutionVertical':microsoft_df['Census_InternalPrimaryDisplayResolutionVertical'].mode().iloc[0],
         'Census_InternalPrimaryDisplayResolutionHorizontal':microsoft_df['Census_InternalPrimaryDisplayResolutionHorizontal'].mode().iloc[0],
         'SMode':microsoft_df['SMode'].mode().iloc[0],
        'IeVerIdentifier':microsoft_df['IeVerIdentifier'].mode().iloc[0],
        'SmartScreen':microsoft_df['SmartScreen'].mode().iloc[0],
        'Firewall': microsoft_df['Firewall'].mode().iloc[0],
        'Wdft_IsGamer':microsoft_df['Wdft_IsGamer'].mode().iloc[0],
        'GeoNameIdentifier':microsoft_df['GeoNameIdentifier'].mode().iloc[0],
       'Census_InternalPrimaryDiagonalDisplaySizeInInches':microsoft_df['Census_InternalPrimaryDiagonalDisplaySizeInInches'].mode().iloc[0]
       }

microsoft_df.fillna(value=values,inplace=True)


In [2]:
microsoft_df.isnull().sum()

ProductName                                          0
EngineVersion                                        0
AppVersion                                           0
AvSigVersion                                         0
IsBeta                                               0
RtpStateBitfield                                     0
IsSxsPassiveMode                                     0
AVProductStatesIdentifier                            0
AVProductsInstalled                                  0
AVProductsEnabled                                    0
HasTpm                                               0
CountryIdentifier                                    0
CityIdentifier                                       0
GeoNameIdentifier                                    0
LocaleEnglishNameIdentifier                          0
Platform                                             0
Processor                                            0
OsVer                                                0
OsBuild   

In [3]:
from sklearn.model_selection import train_test_split
y=microsoft_df['HasDetections']
microsoft_df.drop(columns='HasDetections',inplace=True)


X_train,X_test,y_train,y_test=train_test_split(microsoft_df,y,test_size=0.3,random_state=40)
X_train


ProductName EngineVersion        AppVersion  AvSigVersion  IsBeta  \
15716  win8defender   1.1.15200.1    4.9.10586.1106   1.275.852.0       0   
33740  win8defender   1.1.15200.1        4.10.209.0    1.275.40.0       0   
50864  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1748.0       0   
55393  win8defender   1.1.15200.1   4.18.1807.18075  1.273.1826.0       0   
12703  win8defender   1.1.15100.1   4.18.1807.18075   1.273.933.0       0   
30961  win8defender   1.1.15200.1   4.18.1807.18075   1.275.568.0       0   
23107  win8defender   1.1.15100.1   4.18.1807.18075   1.273.881.0       0   
23490  win8defender   1.1.15100.1   4.18.1807.18075   1.273.879.0       0   
8199   win8defender   1.1.14901.4  4.16.17656.18052   1.269.830.0       0   
20883  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1187.0       0   
33876  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1103.0       0   
52268  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1140.0       0   
27924  win8defender   1.1.15200.1  4.12.17007.18022   1.275.540.0       0   
37258  win8defender   1.1.15200.1   4.18.1807.18075   1.275.826.0       0   
36494  win8defender   1.1.15100.1   4.18.1807.18075   1.273.717.0       0   
18887  win8defender   1.1.15200.1   4.18.1807.18075   1.275.400.0       0   
17944  win8defender   1.1.15200.1  4.12.17007.18011  1.275.1486.0       0   
21929  win8defender   1.1.13701.0      4.10.14393.0   1.241.819.0       0   
24101  win8defender   1.1.15100.1     4.9.10586.672   1.273.642.0       0   
52054  win8defender   1.1.15200.1  4.16.17656.18052   1.275.781.0       0   
6213   win8defender   1.1.15100.1   4.18.1807.18075  1.273.1228.0       0   
2752   win8defender   1.1.15200.1   4.18.1807.18075   1.275.903.0       0   
29281  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1209.0       0   
25049  win8defender   1.1.15100.1   4.18.1807.18075   1.273.658.0       0   
8052   win8defender   1.1.15300.6      4.13.17134.1  1.275.1695.0       0   
12444  win8defender   1.1.15200.1   4.18.1807.18075   1.275.453.0       0   
47771  win8defender   1.1.15100.1   4.18.1807.18075  1.273.1490.0       0   
53756  win8defender   1.1.15200.1   4.18.1807.18075   1.275.167.0       0   
25428  win8defender   1.1.15100.1   4.18.1807.18075  1.273.1527.0       0   
13478  win8defender   1.1.15200.1   4.18.1807.18075   1.275.569.0       0   
...             ...           ...               ...           ...     ...   
37910  win8defender   1.1.15200.1       4.9.10586.0   1.275.164.0       0   
29370  win8defender   1.1.15100.1   4.8.10240.17443   1.273.461.0       0   
3688   win8defender   1.1.15100.1   4.18.1806.18062   1.273.512.0       0   
49652  win8defender   1.1.15100.1   4.18.1807.18075  1.273.1276.0       0   
33628  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1134.0       0   
15630  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1435.0       0   
50383  win8defender   1.1.13903.0    4.13.17134.228   1.247.783.0       0   
36510  win8defender   1.1.15200.1     4.9.10586.916   1.275.727.0       0   
15796  win8defender   1.1.15200.1   4.18.1807.18075  1.275.1115.0       0   
44040  win8defender   1.1.15200.1   4.18.1807.18075   1.275.981.0       0   
5449   win8defender   1.1.15100.1        4.10.209.0   1.273.858.0       0   
53041  win8defender   1.1.14600.4    4.13.17134.191    1.263.48.0       0   
28384  win8defender   1.1.15100.1   4.18.1806.18062   1.273.545.0       0   
34889  win8defender   1.1.15100.1     4.12.16299.15  1.273.1545.0       0   
49595  win8defender   1.1.15100.1   4.18.1807.18075   1.273.781.0       0   
8147   win8defender   1.1.15200.1   4.18.1807.18075  1.275.1107.0       0   
10295  win8defender   1.1.15100.1   4.18.1807.18075  1.273.1056.0       0   
47946  win8defender   1.1.15100.1   4.18.1807.18075  1.273.1329.0       0   
7839   win8defender   1.1.15200.1   4.18.1807.18075  1.275.1435.0       0   
3603   win8defender   1.1.15100.1   4.18.1806.18062   1.273.440.0       0   
1291

In [4]:
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
for col in microsoft_df_dtypes['object']:
    le.fit(X_train[col])
    X_test[col] = X_test[col].map(lambda s: '<unknown>' if s not in le.classes_ else s)
    le.classes_ = np.append(le.classes_, '<unknown>')
    X_train[col] = le.transform(X_train[col])
    X_test[col] = le.transform(X_test[col])
    

C:\Users\sadrool haque\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\sadrool haque\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\sadrool haque\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/

In [5]:
from sklearn.preprocessing import MinMaxScaler
MMS = MinMaxScaler()
X_train_scaled= MMS.fit_transform(X_train)
X_test_scaled= MMS.transform(X_test)
X_train_scaled

array([[1.        , 0.94444444, 0.8630137 , ..., 0.        , 0.        ,
        0.64285714],
       [1.        , 0.94444444, 0.16438356, ..., 0.        , 0.        ,
        0.64285714],
       [1.        , 0.94444444, 0.47945205, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 0.91666667, 0.43835616, ..., 0.        , 0.        ,
        0.71428571],
       [1.        , 0.91666667, 0.47945205, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.94444444, 0.47945205, ..., 0.        , 0.        ,
        0.07142857]])

In [6]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
pca = PCA().fit(X_train_scaled)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
#plt.plot((pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')
plt.show()
pca.components_
plt.show()


<Figure size 640x480 with 1 Axes>

In [7]:
column_list= range(0,40)
pca_1 = PCA(n_components=40)
X_train_new = pca_1.fit_transform(X_train_scaled)
df_train = pd.DataFrame(data=X_train_new, columns=column_list)
df_train

0         1         2         3         4         5         6   \
0     -0.636230  0.781143  0.467779  0.832776  0.136569 -0.367465  0.420220   
1     -0.877818  0.652778  0.768965  0.719380  0.271452 -0.002986  0.023224   
2      0.650930  0.023831 -1.129182 -0.016417  0.377530 -0.000915 -0.099414   
3      1.270855 -0.688607 -0.090136  0.254831  0.272831 -0.032904  0.099353   
4     -0.805384 -0.174893  0.041367 -0.325685  0.142413 -0.296430 -0.290760   
5      0.656043  0.512505 -0.377950 -0.489420 -0.494671  0.675822  0.011125   
6     -0.944685  0.005446  0.350766 -0.207416  0.445185  0.165768 -0.135720   
7     -0.729765 -0.490786 -0.525568  0.325065  0.361878 -0.175237 -0.217991   
8      1.069550 -0.068345  0.317895 -0.396173  0.268834 -0.377448 -0.019313   
9     -0.754996 -0.223448  0.038221 -0.166498 -0.791602  0.203593  0.433483   
10     0.459880  0.602350 -0.443561 -0.532016  0.246512 -0.212516 -0.039562   
11     0.012625  0.341851 -0.109501 -0.123982 -0.847580  0.250566 -0.059406   
12    -0.717922  0.034525  0.262560  0.105559 -0.824877  0.209030  0.664820   
13     0.625109 -0.911918 -0.049927  0.565103  0.122669 -0.270666 -0.745940   
14    -0.887619  0.229112  0.076148  0.111482 -0.163884 -0.371741  0.144358   
15     1.218117 -0.324445  0.491075 -0.318869 -0.135714 -0.016358  0.181149   
16    -0.833523  0.071505  0.146672  0.021458 -0.782534  0.138597  0.590510   
17     0.374384  0.641759 -0.241228 -0.520345  0.136344 -0.180859 -0.047657   
18    -0.762065  0.666537  0.368891  0.730605  0.180872 -0.536445 -0.071726   
19    -0.129642  0.305044  0.002189  0.009225 -1.030993  0.275137 -0.026076   
20    -0.217312 -0.286962 -0.769882  0.212557  0.007269 -0.158301 -0.744790   
21    -0.736890 -0.014741  0.609383 -0.179285  0.237948  1.399974 -0.268887   
22     1.255547 -0.304225  0.425946 -0.219485 -0.520972  0.195163  0.394156   
23     1.101193  0.286470 -0.054861 -0.414135  0.218127 -0.026015 -0.415042   
24     0.521162 -0.570892  0.574076  0.011116 -0.752144 -0.073075 -0.376588   
25     0.375611 -0.682252 -0.332183  0.447264 -0.601860  0.032657 -0.441311   
26    -0.274119  0.061539 -0.130458 -0.313490 -0.212959 -0.232319 -0.715637   
27    -0.073067  0.045101 -0.124781 -0.553878  0.234754 -0.266387  0.588736   
28    -0.636690 -0.356603 -0.331461  0.651955 -0.533508  0.441823  0.605402   
29     0.646387 -0.931713 -0.000677  0.495642 -0.103425 -0.249933 -0.417671   
...         ...       ...       ...       ...       ...       ...       ...   
39699 -0.618188  0.804088  0.254448  0.594135  0.386803 -0.380836  0.038492   
39700 -0.091264  0.870560 -0.649219  1.302433  0.794592 -0.374119  0.836977   
39701 -0.629124 -0.783337  0.085105  0.286462  0.928921  0.760356 -0.136357   
39702  0.703027 -0.475870  0.701465  0.001602 -0.041986 -0.175555 -0.730672   
39703  0.482050 -0.505443  0.643175 -0.049115 -0.226067 -0.282737 -0.554405   
39704  0.501818  0.566751 -0.441809 -0.588052 -0.118755  0.193615 -0.229819   
39705 -0.849757 -0.058566  0.293747 -0.306141  0.290749  0.218857 -0.124253   
39706 -0.676639  0.256535 -0.306905  1.352048  0.297473 -0.104015  0.117481   
39707  0.652344 -1.041221  0.126760  0.624351 -0.657441  0.187986 -0.294789   
39708  0.326300  0.251418 -0.218135 -0.568598 -0.125486  0.828890  0.323606   
39709 -0.682024  0.695396  0.459182  0.691235 -0.333673 -0.112131  0.207286   
39710  0.007513  0.260254  0.269516 -0.175252 -0.383616  1.676829 -0.475041   
39711  0.541950  0.585776 -0.304825 -0.622031  0.136986  0.224910 -0.311025   
39712  1.135418  0.024966  0.388309 -0.366084  0.393175 -0.202162 -0.109384   
39713 -0.845422  0.117389  0.160617 -0.053786 -0.208433 -0.185755  0.170981   
39714 -0.049606  0.052220 -0.150603 -0.544053  0.513798 -0.221344  0.410780   
39715 -0.090255  0.187792  0.377337 -0.144817 -0.277154  1.317118 -0.212028   
39716  1.010328 -0.169414  0.343383 -0.380871  0.033063 -0.350368  0.117059   
39717 -0.811852 -0.173011  0.518590 -0.125722  0.458553  0.3449

In [8]:
X_test_new = pca_1.transform(X_test_scaled)
df_test = pd.DataFrame(data=X_test_new,columns=column_list)
df_test

0         1         2         3         4         5         6   \
0      0.591648  0.040237 -0.881457  0.102742  0.239820  0.033789  0.034580   
1     -0.294346 -0.461198  0.620053 -0.066767  0.075005 -0.459506 -0.048410   
2      1.230187 -0.096583  0.517956 -0.208565 -0.644429  0.508857  0.234484   
3      1.225193 -0.760076 -0.307580  0.313133 -0.267074  0.149327  0.355447   
4     -0.033804 -0.253232 -0.733905  0.315796  0.035549 -0.053261 -0.592949   
5     -0.129861  0.248994  0.379010 -0.211091  0.551385  0.924940 -0.669292   
6     -0.184938  0.092302 -0.068725 -0.356407 -0.283453 -0.083275 -0.630680   
7     -0.697607 -0.516610 -0.620750  0.300274  0.225628 -0.238247 -0.071762   
8     -0.772128  0.156798  0.104379 -0.026610 -0.060698 -0.358881  0.198825   
9      0.477424  0.893123 -0.341864 -0.296789  0.204224 -0.281371  0.079235   
10    -0.170578 -0.058126  0.249605 -0.312807  0.344442  0.412471 -0.743503   
11    -0.139796  0.162851 -0.008223 -0.529453  0.565172 -0.222772  0.466716   
12     1.236789 -0.648604 -0.214568  0.317402  0.200517 -0.177377  0.093806   
13    -0.666380 -0.168751  0.493018 -0.319991  0.403247  0.288676  0.113497   
14    -0.619807 -0.266983  0.314695 -0.130810 -0.592117  0.679398  0.461841   
15     0.427783  1.436727 -0.149789  0.605235  0.220975 -0.385397  0.351540   
16    -0.761106 -0.015544  0.057806 -0.250054  0.132453 -0.406543 -0.248634   
17    -0.000748  0.567434 -0.022952 -0.032956 -0.924166  0.553198 -0.305749   
18    -0.137955  1.166202  0.310825  1.077609 -0.829815  0.200781  0.281956   
19     1.200594 -0.248310  0.288942 -0.180787 -0.577537  0.049863  0.507577   
20    -0.732694 -0.583945 -0.506987  0.260818  0.208451 -0.155747 -0.163680   
21     0.209081  0.316281  0.527068 -0.385150  0.669939  1.586062 -0.696686   
22    -0.631583 -0.469207 -0.713226  0.303612  0.350576 -0.229490 -0.066489   
23    -0.123683  0.366625 -0.135396 -0.150458 -0.703204  0.333580 -0.246868   
24    -0.757839 -0.000737 -0.127799 -0.362871  0.125889 -0.266744  0.011053   
25     0.067906  0.076372 -0.160100 -0.235121 -0.820815  0.133717 -0.156717   
26    -0.122800  0.396333 -0.031597 -0.168163 -0.155400 -0.222688 -0.646580   
27    -0.052597  1.009292  0.244453  0.752713 -0.755603  0.378134 -0.404611   
28    -0.725834 -0.269359  0.100210 -0.228476 -0.337172 -0.113199  0.121150   
29    -0.057201 -1.184744  0.310461  0.533539  0.430035 -0.407211 -0.178610   
...         ...       ...       ...       ...       ...       ...       ...   
16997 -0.187768  0.082071 -0.182717 -0.646277  0.456269 -0.210524  0.450530   
16998 -0.667072 -0.050332  0.081763 -0.343944 -0.081506 -0.267240  0.133067   
16999 -0.843126 -0.166225  0.471504 -0.173163  0.194013  0.372153  0.090146   
17000  0.717177 -0.952883  0.035357  0.714797 -0.472909  0.062143 -0.274785   
17001  1.268481 -0.729094 -0.114899  0.361190 -0.289576  0.208479  0.404859   
17002 -0.657320 -0.106465  0.203022 -0.095079 -0.777220  0.177814  0.498522   
17003 -0.161081  0.009785  0.433573 -0.473246  0.897998  0.822076  0.552111   
17004 -0.468768 -0.400219  0.130081  0.354104  0.661218  1.371269 -0.293244   
17005 -0.719917  0.015148  0.008577 -0.250077  0.160753 -0.368767  0.046352   
17006  1.277829  1.159594  0.633762  0.990270  0.384965 -0.198612 -0.020090   
17007 -0.831318  0.178356  0.082544  0.028216  0.077735 -0.392919 -0.032824   
17008 -0.765457 -0.321509  0.672907 -0.241752  0.397956  0.655256  0.067994   
17009 -0.671581 -0.685852  0.120609  0.529322  0.524384  1.374432  0.111817   
17010  1.264331  0.132963  0.221966  1.459205 -0.120973  0.039386  0.670814   
17011 -0.159468 -0.166477 -0.869613  0.363833 -0.641366  0.209705 -0.331204   
17012  0.712704 -0.920952  0.147954  0.629733  0.021772 -0.097129 -0.496448   
17013 -0.024787 -1.249422  0.335798  0.525985  0.251675 -0.269244 -0.154944   
17014 -0.947355 -0.100772  0.320990 -0.330224  0.410385  0.256863 -0.135666   
17015  0.410056  1.706943  0.060825  0.720607  0.737141  0.1721

In [9]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(df_train,y_train)
y=y.astype('int')
predicted = LR.predict(df_test)
predicted


C:\Users\sadrool haque\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [10]:
from sklearn.metrics import f1_score,precision_score,confusion_matrix
f1_score(y_test,predicted)

0.6221237069875448

In [11]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB.fit(df_train,y_train)
predicted2=NB.predict(df_test)
predicted2

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [12]:
confusion_matrix(y_test,predicted2)

array([[3650, 4915],
       [2502, 5960]], dtype=int64)

In [13]:
f1_score(y_test,predicted2)

0.6164348140869835

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
gra= GradientBoostingClassifier()
gra.fit(X_train,y_train)
gra_pred=gra.predict(X_test)
gra_pred

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [15]:
f1_score(y_test,gra_pred)


0.6414565826330533

In [16]:
from sklearn.model_selection import RandomizedSearchCV
para_dict= { 
             'learning_rate': [0.3,0.4,0.5,0.9],
              'n_estimators': [20,30,40,50],
            'min_samples_split':[2,3,5,10],
            'max_depth':[1,2,3,9],
            'min_samples_leaf': [1,2,3,8],
            'max_leaf_nodes': [4,5,6,7],
            }
gra= GradientBoostingClassifier()
rsc=RandomizedSearchCV(gra,para_dict,cv=5)
rsc.fit(X_train,y_train)
rsc.best_params_

{'n_estimators': 30,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_leaf_nodes': 7,
 'max_depth': 3,
 'learning_rate': 0.4}

In [17]:
rsc.best_score_

0.6119711042311662

In [19]:
from sklearn.ensemble import GradientBoostingClassifier

GBC=GradientBoostingClassifier(n_estimators=50,min_samples_split=3,min_samples_leaf=8,max_leaf_nodes=6,max_depth=3,learning_rate= 0.3)

GBC.fit(X_train,y_train)
GBC.predict(X_test)


print(f'confussion matrix =\n {confusion_matrix(y_test,GBC.predict(X_test))}')
print(f'GBC.score= {GBC.score(X_train,y_train)}')
print(f'f1_score = {f1_score(y_test,GBC.predict(X_test))}')
print(f'precision_score = {precision_score(y_test,GBC.predict(X_test))}')

confussion matrix =
 [[4537 4028]
 [2612 5850]]
GBC.score= 0.6265951823604924
f1_score = 0.6379498364231189
precision_score = 0.5922251467908484


In [20]:
from sklearn.ensemble import AdaBoostClassifier
ada= AdaBoostClassifier()
ada.fit(X_train,y_train)
ada_pred=ada.predict(X_test)
ada_pred

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [21]:
f1_score(y_test,ada_pred)

0.6325591586327782

In [ ]:
microsoft_df